// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package com.krusty84.fileconnector.resources;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Iterator;

import org.eclipse.lyo.oslc4j.core.annotation.OslcAllowedValue;
import org.eclipse.lyo.oslc4j.core.annotation.OslcDescription;
import org.eclipse.lyo.oslc4j.core.annotation.OslcMemberProperty;
import org.eclipse.lyo.oslc4j.core.annotation.OslcName;
import org.eclipse.lyo.oslc4j.core.annotation.OslcNamespace;
import org.eclipse.lyo.oslc4j.core.annotation.OslcOccurs;
import org.eclipse.lyo.oslc4j.core.annotation.OslcPropertyDefinition;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRdfCollectionType;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRange;
import org.eclipse.lyo.oslc4j.core.annotation.OslcReadOnly;
import org.eclipse.lyo.oslc4j.core.annotation.OslcRepresentation;
import org.eclipse.lyo.oslc4j.core.annotation.OslcResourceShape;
import org.eclipse.lyo.oslc4j.core.annotation.OslcTitle;
import org.eclipse.lyo.oslc4j.core.annotation.OslcValueType;
import org.eclipse.lyo.oslc4j.core.model.AbstractResource;
import org.eclipse.lyo.oslc4j.core.model.Link;
import org.eclipse.lyo.oslc4j.core.model.Occurs;
import org.eclipse.lyo.oslc4j.core.model.OslcConstants;
import org.eclipse.lyo.oslc4j.core.model.Representation;
import org.eclipse.lyo.oslc4j.core.model.ValueType;

import com.krusty84.fileconnector.resources.Oslc_fsnspDomainConstants;
import com.krusty84.fileconnector.resources.Oslc_fsnspDomainConstants;
// Start of user code imports
// End of user code

@OslcNamespace(Oslc_fsnspDomainConstants.FILE_NAMESPACE)
@OslcName(Oslc_fsnspDomainConstants.FILE_LOCALNAME)
@OslcResourceShape(title = "File Shape", description = "The resource represents real file(-s) on file system", describes = Oslc_fsnspDomainConstants.FILE_TYPE)
public interface IFile
{


    @OslcName("FileName")
    @OslcPropertyDefinition(Oslc_fsnspDomainConstants.FILE_SYSTEM_NAMSPACE + "FileName")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    @OslcMemberProperty(true)
    public String getFileName();

    @OslcName("LastModifiedTime")
    @OslcPropertyDefinition(Oslc_fsnspDomainConstants.FILE_SYSTEM_NAMSPACE + "LastModifiedTime")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.DateTime)
    @OslcReadOnly(false)
    public Date getLastModifiedTime();

    @OslcName("FileDescription")
    @OslcPropertyDefinition(Oslc_fsnspDomainConstants.FILE_SYSTEM_NAMSPACE + "FileDescription")
    @OslcOccurs(Occurs.ExactlyOne)
    @OslcValueType(ValueType.String)
    @OslcReadOnly(false)
    public String getFileDescription();


    public void setFileName(final String fileName );
    public void setLastModifiedTime(final Date lastModifiedTime );
    public void setFileDescription(final String fileDescription );
}

