// Start of user code Copyright
/*
 * Copyright (c) 2020 Contributors to the Eclipse Foundation
 *
 * See the NOTICE file(s) distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Simple
 *
 * This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
 */
// End of user code

package com.krusty84.fileconnector.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface Oslc_fsnspDomainConstants
{
    // Start of user code user constants
    // End of user code

    /**
     * @deprecated use {@link Oslc_fsnspDomainConstants#FILE_SYSTEM_NAMSPACE} or {@link Oslc_fsnspDomainConstants#FILE_SYSTEM_DOMAIN_NAME} instead
     */
    @Deprecated(since = "5.0.1")
    public static String FILE_SYSTEM_DOMAIN = "http://your.organisation.domain/oslc_fsnsp#";
    public static String FILE_SYSTEM_DOMAIN_NAME = "File System";
    public static String FILE_SYSTEM_NAMSPACE = "http://your.organisation.domain/oslc_fsnsp#"; //Vocabulary namespace for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined 
    public static String FILE_SYSTEM_NAMSPACE_PREFIX = "oslc_fsnsp"; //Vocabulary prefix for the resources and resource properties, when no explicit vocabulary (describes, or propertyDefinition) is defined

    public static String FILE_PATH = "file";  //the relative path of the resource shape URL.
    public static String FILE_NAMESPACE = Oslc_fsnspDomainConstants.FILE_SYSTEM_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String FILE_LOCALNAME = "File"; //localName of the rdfs:class the resource describes
    public static String FILE_TYPE = FILE_NAMESPACE + FILE_LOCALNAME; //fullname of the rdfs:class the resource describes
}
